server:
  port: 30150

mybatis:
  mapper-locations:
    - classpath*:mappers/*.xml
    - classpath*:**/mapper/common/*Mapper.xml
    - classpath*:**/mapper/embedded/*Mapper.xml
  config-location: classpath:jpaConfig.xml
mybatis-plus:
  mapper-locations: ${mybatis.mapper-locations}
  config-location: ${mybatis.config-location}

spring:
  application:
    name: dict
  mvc:
    resource-handler-registry:
      entries:
        - handlers: /ui-dict/**
          locations: classpath:/static/ui-dict/



  main:
    allow-bean-definition-overriding: true

  messages:
    basename: i18n/message
    encoding: UTF-8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:

      jdbc-url: jdbc:h2:~/.h2/hbq969/h-dict
      driver-class-name: org.h2.Driver
      username: foo
      password: bar
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  # 接口缓存
  cache:
    ext:
      enable: true
      juc:
        allow-null-values: true
        max-capacity: 2000

  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
        port: ${server.port}
        tags: path=/${spring.application.name},port=${server.port},secure=false
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        health-check-path: /common/health
        health-check-interval: 10s
      host: localhost
      port: 8500


knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: 123456

swagger:
  api-info:
    enable: true
    title: web应用Restful API
    description: web应用Restful API
    termsOfServiceUrl: http://127.0.0.1:${server.port}
    version: v1.0
    license: Apache LICENSE-2.0
    licenseUrl: https://apache.org/licenses/LICENSE-2.0.txt

# 数据字典管理
dict:
  enabled: true
  dict-token: hbq969@gmail.com
  reload:
    cron: 0,30 * * * * *
  map-key-prefix: fmt

# 分布式锁
lock:
  spi:
    redis:
      enabled: false
      standard:
        host: docker.for.mac.host.internal
        port: 6379

# restful接口加解密
encrypt:
  config:
    enabled: true
  restful:
    aes:
      enabled: false
      charset: utf-8
      show-log: true
      key: x
    rsa:
      enabled: false
      charset: utf-8
      show-log: true
      private-key: x
      public-key: x

# restful接口日志记录
advice:
  log:
    enabled: true
  restful-limit:
    enabled: true